name: Admin.NET-Sync

on:
  repository_dispatch:
  workflow_dispatch:

env:
  repo_url: 'https://gitee.com/zuohuaijun/Admin.NET.git'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:    
      - name: Init Env
        run: |
          sudo -E apt-get -qq install git curl wget openssl -y
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      - name: Domain tools
        uses: bfmen/cn-domain-tools@main

      - name: Configure Git
        working-directory: /workdir
        run: |
          git config --global user.name "ActionBot"
          git config --global user.email "ibfmen@gamil.com"

      - name: Clone Admin.NET
        working-directory: /workdir
        run: |
          git clone https://github.com/bfmen/Admin.NET.git
          cd Admin.NET
          git checkout v2

      - name: Merge Upstream
        working-directory: /workdir/Admin.NET
        run: |
          git remote add upstream ${{ env.repo_url }}
          git fetch upstream
          git remote
          git checkout v2
          git merge upstream/v2 --no-edit

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.UPDATE_TOKEN }}
          directory: /workdir/Admin.NET
          branch: v2
          repository: bfmen/Admin.NET
          force: true
