name: WarpPlus-Docker
on:
  repository_dispatch:
  workflow_dispatch:

env:
  repo_url: 'https://github.com/bepass-org/warp-plus.git'
  docker-repo: 'bfmen/warp-plus'
  docker-file-path: ''
  platforms: 'linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64'

jobs:  
  build:  
    runs-on: ubuntu-latest
        
    steps:  
      - name: 'Checking'
        uses: actions/checkout@v4

      - name: Init Env
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          sudo apt-get install tree
          sudo mkdir -p ./workdir
          sudo chown $USER:$GROUPS ./workdir
          echo "======== 🚀Directory structure ========"
          tree -L 3

      - name: Clone Repo
        run: |
          git clone ${{ env.repo_url }} ./workdir
      
      - name: Repo Tag
        working-directory: ./workdir
        id: tag
        run: |
          echo "repo_tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT
          echo "release_tag=$(date +"%Y.%m.%d-%H%M%S")" >> $GITHUB_OUTPUT >> $GITHUB_OUTPUT

      - name: Modify file
        run: |
          tree -L 3
          echo "======== 🚀Dockerfile Info ========"
          cp -rf ./bin/warp/Dockerfile ./workdir/
          cat ./workdir/Dockerfile
          echo "======== 🚀Warp Configuration ========"
          cp -rf ./bin/warp/DockerEntrypoint.sh ./workdir/
          cp -rf ./bin/warp/example_config.json ./workdir/
          cat ./workdir/example_config.json

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker
        id: docker
        uses: docker/build-push-action@v5
        with:
          context: ./workdir
          push: true
          file: ${{ env.docker-file-path }}
          platforms: ${{ env.platforms }}
          tags: | 
            ${{ env.docker-repo }}:latest
            ${{ env.docker-repo }}:${{ steps.tag.outputs.repo_tag }}
      
      - name: Image digest
        run: echo ${{ steps.docker.outputs.digest }}

      - name: Docker pull to save
        run: |
          docker pull --platform linux/amd64 ${{ env.docker-repo }}:latest
          docker save -o warp-plus-amd64-${{ steps.tag.outputs.repo_tag }}.tar ${{ env.docker-repo }}:latest
          docker rmi ${{ env.docker-repo }}:latest
          docker pull --platform linux/arm64 ${{ env.docker-repo }}:latest
          docker save -o warp-plus-arm64-${{ steps.tag.outputs.repo_tag }}.tar ${{ env.docker-repo }}:latest
        
      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v1
        if: success() && !cancelled()
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: ${{ github.workflow }} - ${{ steps.tag.outputs.repo_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          body: | 
            Release Note:
            - [ DockerHub🐬 ](https://hub.docker.com/r/${{ env.docker-repo }})
            - 🎯Use: `docker pull bfmen/warp-plus:latest`
            - 👇Or download the Docker image and import it manually
          files: | 
            ${{ steps.docker.outputs.metadata }}
            warp-plus-amd64-${{ steps.tag.outputs.repo_tag }}.tar
            warp-plus-arm64-${{ steps.tag.outputs.repo_tag }}.tar
